### ISSUE TITLE
Issue with Temp script

### ISSUE THREAD

**Issue by killmasta93** [NoLooseEnds/Scripts#10]
Hi,
I was wondering if someone else has had this issue before on r610 running proxmox.

currently getting this error

```
root@prometheus:~/Scripts/R710-IPMI-TEMP# sh R710-IPMITemp.sh 
R710-IPMITemp.sh: 31: R710-IPMITemp.sh: [[: not found
```
Thank you

**Comment by bradmccormack** [comment]
Hi @killmasta93 

That looks like you are calling it with sh not bash.

sh probably can't interpret that syntax. Just mark the script as executable (chmod +x) and run it without "sh".

That will use bash and the syntax will be correct.
