### ISSUE TITLE
XenServer better solution

### ISSUE THREAD

**Issue by backamblock** [NoLooseEnds/Scripts#2]
Hey there, i am using Xenserver where you can access the coretemps with lm_sensors
Please tell me how to change this line to fit in there

TEMP=$(ipmitool -I lanplus -H $IPMIHOST -U $IPMIUSER -P $IPMIPW sdr type temperature |grep Ambient |grep degrees |grep -Po '\d{2}' | tail -1)

thank you

**Comment by NoLooseEnds** [comment]
Hi, if you want to use this script you need to modify the command to use lm_sensors, and then modify the output to be one digit number. I don't use lm_sensors myself, but you should be able to mange to do it via som googlefoo (I googled quick, and found this that you could build upon: https://blog.lbdg.me/r710-quieter/)

Closing this.

**Comment by backamblock** [comment]
thank you
