### ISSUE TITLE
fan speed commands don't stick

### ISSUE THREAD

**Issue by tresbizarre** [NoLooseEnds/Scripts#6]
If I try to set the fan speed via the

>  ipmitool -I lanplus -H <iDracip> -U root -P <rootpw> <command> <rootpw> <command>

command, the fans slow down for several seconds and then return to the previous speed.  Any Idea how to change this behavior?.

**Comment by Tucker2015** [comment]
Are you using the Manual speed setting control first ?

raw 0x30 0x30 0x01 0x00

**Comment by NoLooseEnds** [comment]
Closing this.
