### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by ajugland** [NoLooseEnds/Scripts#9]
Hi I get this when i run it on a R720 and a R710.

/tmp/user.scripts/tmpScripts/Dell Fan NoLooseends/script: line 39: systemd-cat: command not found
Temperature is OK ( C)

**Comment by NoLooseEnds** [comment]
I'm not using this anymore, but my guess is that you're either missing "systemd-cat" or don't have the correct binary paths set up. Closing this, since it's not an issue with thee script.

**Comment by jdmallen** [comment]
@ajugland [This](https://github.com/jdmallen/dell-ipmi-fan-control-monitor) might be worth your consideration, though it's a bit more complex to set up than a bash script. (Thanks @NoLooseEnds for the inspiration to make my project, btw.)

**Comment by ajugland** [comment]
Thanks alot

Do you have any better scripts to suggest for R710 or R720? You say bash
script, but where do i run those?

ons. 15. apr. 2020, 20:40 skrev J.D. Mallen <notifications@github.com>:

**Comment by ajugland** [comment]
I thaught it was a bash script actually because when I put it in custom
script in unraid it starts with #!/bin/bash

tor. 16. apr. 2020, 14:49 skrev Andre Ugland <ajugland@gmail.com>:

**Comment by NoLooseEnds** [comment]
It is a bash script. 

You get an error when trying to run systemd-cat binary called on by the script. I have never used Unraid, so you need to start your troubleshooting there. 

Do Unraid even use systemd (more specific systemd-cat)? 

(You could try [@spacelama's perl fork of this script](https://github.com/spacelama/Scripts))

**Comment by ajugland** [comment]
Donno. But script looked so good. I have a very basic one now. Used alot of
time to get one that worked. If idrac licence stops then my server will
burn too. Not so safe going via ip

tor. 16. apr. 2020, 15:00 skrev NoLooseEnds <notifications@github.com>:
